version: '1.0'

networks:
  dmz:

services:

# Cowrie service
  cowrie:
    container_name: cowrie
    restart: always
    networks:
     - dmz
    cap_add:
     - NET_BIND_SERVICE
    ports:
     - "22:2222"
     - "23:2223"
    image: "amhiggin/cyber-incident-monitor"
    volumes:
     - /data/cowrie/downloads:/cowrie/cowrie-git/dl
     - /data/cowrie/keys:/cowrie/cowrie-git/etc
     - /data/cowrie/log:/cowrie/cowrie-git/log
     - /data/cowrie/log/tty:/cowrie/cowrie-git/log/tty

